# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'FGP' do
# 不显示第三方中的警告
inhibit_all_warnings!
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire',              '~> 4.7'
    pod 'Kingfisher',             '~> 4.10.0'
    pod 'Moya',                   '~> 11.0'
    pod 'Moya/RxSwift',           '~> 11.0'
    pod 'ObjectMapper',           '~> 3.3.0'
    pod 'MagiRefresh',            '~> 0.0.8'
    pod 'MagiTabBarController',   '~> 0.1.0'
    pod 'MagiPhotoBrowser'
    pod 'SnapKit',                '~> 4.2.0'
    pod 'RxSwift',                '~> 4.3.1'
    pod 'RxCocoa',                '~> 4.3.1'
    pod "Texture"
    pod "QuickCocoa"

  # Pods for FGP

end
